Пользовательские истории
mp-hl-2021/lenkeforkortelse pull request #1
Opened 2021-02-15 18:42 UTC by pavlov200912

Пользовательские истории для проекта сокращения ссылок.

2021-02-19 06:14 UTC, NekoNe requested changes

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как пользователь, я хочу использовать выданную мне короткую ссылку и переходить на соответствующий сайт без задержек.
It is really a good point about latency. 
From manager's perspective I would be pleased to hear "without latency" but from engineering perspective I would ask: How am I supposed to do that?
Could you clarify what does it mean "without latency"?

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как пользователь, я хочу получать короткую уникальную ссылку по длинному URL, чтобы было проще её использовать.
Does user make short link herself? Or your service should generate it randomly?

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как зарегистрированный пользователь, я хочу иметь возможность просматривать уже созданные мною ранее сокращения для ссылок, чтобы использовать их повторно.
We have two different interpretations of this story with Dmitri.
Interpretations:

1. User can see a list of all of her shot links, in order to be able to remember them.
2. User can assign new link to her old shot links

So, what does it mean?

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как пользователь, я хочу использовать выданную мне короткую ссылку и переходить на соответствующий сайт без задержек.
And as a user why do I want to follow shot link without latency?

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как зарегистрированный пользователь, я хочу иметь возможность удалять созданные мною ранее сокращения для ссылок.
You missed motivational part in this story.

Should you specify the behavior of a removed link?

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как зарегистрированный пользователь, я хочу, чтобы действия от моего аккаунта мог выполнять исключительно я, чтобы никто не смог изменить мои ссылки.
I'll leave a comment in Slack.

2021-02-19 06:14 UTC, NekoNe commented on user-stories.md
> +- Как зарегистрированных пользователь, я хочу чтобы созданные мною ранее ссылки и их полные версии видел исключительно я, чтобы обеспечить приватность.
If I place my short link in some social media, how does your service will protect my short link?
Do you mean that only I as a user could follow my short links?

2021-02-19 17:06 UTC, pavlov200912 commented on user-stories.md
> +- Как пользователь, я хочу получать короткую уникальную ссылку по длинному URL, чтобы было проще её использовать.
Who is "herself"?

2021-02-19 18:08 UTC, pavlov200912 commented
@NekoNe fixed!

2021-02-20 12:00 UTC, M0nsteR approved these changes
Good work,
ACK

2021-02-21 10:46 UTC, NekoNe approved these changes

2021-02-22 11:06 UTC, merged